language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - flake8
  - coverage run -m pytest

after_success:
  - export "$CODECOV_TOKEN"
  - bash <(curl -s https://codecov.io/bash)
