language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - flake8
  - mypy
  - black
  - coverage run -m pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: heroku
  api_key: HEROKU_TOKEN
  app: save-leisure
