# Generated by Django 3.1.3 on 2020-11-10 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemType",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                ("data_type", models.CharField(default="item", max_length=50)),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("telegram_id", models.IntegerField()),
                ("registration_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ToSeeItem",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("message_id", models.IntegerField()),
                ("date_received", models.DateField()),
                ("raw_data", models.CharField(max_length=1000)),
                (
                    "data_type",
                    models.ForeignKey(
                        default="item",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="bot.itemtype",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bot.user"
                    ),
                ),
            ],
        ),
    ]
