# Generated by Django 3.1.3 on 2020-11-10 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
